name: Build
on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    if: startsWith(github.repository, 'ModdingX/') # don't run this in forks
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          path: base

      - name: 'Remove files not needed in gist'
        shell: bash
        working-directory: base
        run: |
          rm -rf .github .gitignore .gitattributes README.md LICENSE
          
      - name: 'Commit and Push'
        shell: bash
        working-directory: base
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git remote set-url origin https://noeppi-noeppi:${{ GIST_TOKEN }}@gist.github.com/61eebcebf505f065f1fcf9064a737fb5.git
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Deploy'
          git push --force
